### ISSUE TITLE
1.19 QuickCarpet Alongside Carpet crashes.

### ISSUE THREAD

**Issue by HellyTubbies** [QuickCarpet/QuickCarpet#144]
- Minecraft: 1.19
- QuickCarpet: 3.5.0+1.19

```
This is a Fabric Crash Error.
Error Code:
[07:41:56] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[07:41:56] [ForkJoinPool-1-worker-1/WARN]: The mod "moreculling" contains invalid entries in its mod json:
- Unsupported root entry "includes" at line 43 column 13
[07:41:56] [main/WARN]: Mod resolution failed
[07:41:56] [main/INFO]: Immediate reason: [NEG_HARD_DEP quickcarpet 3.5.0+1.19 {breaks carpet @ [*]}, ROOT_FORCELOAD_SINGLE carpet 1.4.79, ROOT_FORCELOAD_SINGLE quickcarpet 3.5.0+1.19]
[07:41:56] [main/INFO]: Reason: [NEG_HARD_DEP quickcarpet 3.5.0+1.19 {breaks carpet @ [*]}]
[07:41:56] [main/INFO]: Fix: add [], remove [], replace [[quickcarpet 3.5.0+1.19] -> add:quickcarpet 1 ([(-âˆž,âˆž)])]
[07:41:56] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'QuickCarpet' (quickcarpet) 3.5.0+1.19 with any version that is compatible with:
		 - carpet 1.4.79
Unmet dependency listing:
	 - Mod 'QuickCarpet' (quickcarpet) 3.5.0+1.19 is incompatible with any version of mod 'Carpet Mod' (carpet), but a matching version is present: 1.4.79!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

```
I'm also using Carpet Tis Addition and CarpetExtra.

**Comment by HellyTubbies** [comment]
would u also like the full Minecraft Log or is this okay?

**Comment by skyrising** [comment]
QuickCarpet and carpet are not compatible with each other

**Comment by HellyTubbies** [comment]
Oh. Thats unfortunate. thank you!
